#!/bin/bash

echo '-------------------------------------------'
echo " Repertoire : $REP "
echo " Nom du job : $PBS_JOBNAME "
echo '-------------------------------------------'
echo " Numero du noeud : "; cat $PBS_NODEFILE
echo '-------------------------------------------'
printenv
echo '-------------------------------------------'

# Recherche du numero du job
JOBID=${PBS_JOBID%%.*}

# Construction du nom d'un fichier de sortie
OUTFILE=$PBS_O_WORKDIR/$PBS_JOBNAME.$JOBID.out

# Lancement de l'executable
cd $REP
make > $OUTFILE
